version: '3.7'

services:
  web:
    build: .
    command: python3 /Users/hubertyu/Documents/django_professional/manage.py runserver 0.0.0.0:8000
    volumes: 
      - .:/Users/hubertyu/Documents/django_professional
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: