version: '3.7'

services:
  web:
    build: .
    command: python3 /Users/hubertyu/Documents/django_professional/manage.py runserver 0.0.0.0:8000
    environment:
      - NEW_SECRET_KEY=%8&00#qd3shk1)#7-hs_3g5vv^m_zf_cf+9el2-3-@yo%4)=o#
      - DEBUG=1
      - STRIPE_TEST_PUBLISHABLE_KEY=pk_test_ROBH6oJx2LGpsVz5lpR38KUu005EO4i2iq
      - STRIPE_TEST_SECRET_KEY=sk_test_FPi5HlqpPVMljV1OaPYZPJsi00deDOFD7f
    volumes: 
      - .:/Users/hubertyu/Documents/django_professional
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: