# Generated by Django 2.2.3 on 2019-09-11 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_auto_20190911_0944'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('wimor9_status', 'Can read all books')]},
        ),
    ]
